### ISSUE TITLE
ERROR (MainThread) [frontend.js.latest.202012120] https://xxxx.duckdns.org:8123/hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js:163:22 NotSupportedError: Cannot define multiple custom elements with the same tag name

### ISSUE THREAD

**Issue by JanHACS** [ofekashery/vertical-stack-in-card#100]
Since last HA update I have this error on my HA log...

ERROR (MainThread) [frontend.js.latest.202012120] https://xxxx.duckdns.org:8123/hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js:163:22 NotSupportedError: Cannot define multiple custom elements with the same tag name

Any idea how to solve it?

Thanks in advance :-)

**Comment by ofekashery** [comment]
It looks like you're importing the ``vertical-stack-in-card.js`` file twice, take a look at your ``resource`` list.
