### ISSUE TITLE
Theme Issue

### ISSUE THREAD

**Issue by hm1234** [ofekashery/vertical-stack-in-card#109]
I am having an issue where the vertical stack in the card is darker compared to my other buttons. Using the same theme on both.
![image](https://user-images.githubusercontent.com/13208530/113868233-7421a400-977d-11eb-9d22-6ba70fb10c16.png)
![image](https://user-images.githubusercontent.com/13208530/113868258-7dab0c00-977d-11eb-87ee-a000422cee97.png)
![image](https://user-images.githubusercontent.com/13208530/113868329-90254580-977d-11eb-81d4-67f85cc48595.png)
![image](https://user-images.githubusercontent.com/13208530/113868374-9b787100-977d-11eb-86ca-0107be922440.png)

**Comment by ppanagiotis** [comment]
Same here. :/
