### ISSUE TITLE
Stopped working after last update

### ISSUE THREAD

**Issue by hudsonbrendon** [ofekashery/vertical-stack-in-card#114]
Hi, unfortunately the card stopped working for me after the last update (2021.12.1), can you take a look at what it could be?

![image](https://user-images.githubusercontent.com/5201888/146096399-e6ecd87a-f2c8-4f83-aca3-df55dc7b670c.png)

**Comment by magenbrot** [comment]
Hi  @hudsonbrendon, this repo is about 'custom:vertical-stack-in-card'. It seems you're using a different card.

**Comment by mdezotti** [comment]
@hudsonbrendon: I've solved this issue's error by replacing:

```
- type: custom:hui-vertical-stack-card
```
with 

```
- type: custom:hui-element
  card_type: vertical-stack
```
You need to install via Hacs "hui-element" if you don't have it

[https://github.com/thomasloven/lovelace-hui-element](url)
