### ISSUE TITLE
Need documentation for styles?

### ISSUE THREAD

**Issue by gig4ls** [ofekashery/vertical-stack-in-card#119]
Tried adding css attributes to the styles option, none of them work. Examples are as follows:

Adding a background image, changing text color from default white to black:
```
styles: |
  ha-card {
    color: black;
    background-image: url('/local/img/litter-robot.png');
    background-size: contain;
  } 
```

Changing text color to red, per the example in #110 :
```
styles:
  '--ha-card-color': red;
```

Not sure if I'm missing something?

**Comment by EmJay276** [comment]
I had the same issue
```
styles:
  background-color: red
```
will work.
The syntax is:
```
styles:
  <CSS Property>: <value>
```
See: https://www.w3schools.com/cssref/

**Comment by gig4ls** [comment]
> I had the same issue
> 
> ```
> styles:
>   background-color: red
> ```

Interesting, this doesn't work for me. Also, a similar syntax with background image doesn't work for me.

**Comment by EmJay276** [comment]
If an ha-card inside this ha-card will set the color, it will overwrite the color. 
I couldn't change the textcolor (was set inside again), so I just used the card mod plugin, wich works perfect
https://github.com/thomasloven/lovelace-card-mod

**Comment by JCHH2** [comment]
> > I had the same issue
> > ```
> > styles:
> >   background-color: red
> > ```
> 
> Interesting, this doesn't work for me. Also, a similar syntax with background image doesn't work for me.

same here - I'm trying to remove the borders that have been visible since about 2022.10
```
styles:
  border: none
```
I cannot find any style that works.

**Comment by ofekashery** [comment]
Hi @JCHH2, the `styles` property is used for the inner cards. To change the root-card style, please use [card-mod](https://github.com/thomasloven/lovelace-card-mod), as mentioned above.

**Comment by JCHH2** [comment]
Oh, OK, thanks.

`styles` is shown as an option in the docs (with no mention of card-mod).  Has it simply stopped working and `card-mod` is the workaround?
![Screenshot 2023-03-07 at 07 37 30](https://user-images.githubusercontent.com/34644672/223355580-7ff987d6-d4b9-45b8-880b-2704b0f03629.png)

**Comment by JCHH2** [comment]
hang on, I am trying to change the styles of the inner cards!

This is what I have:
![Screenshot 2023-03-07 at 08 56 32](https://user-images.githubusercontent.com/34644672/223372786-e2dfa5d0-5ce0-4645-8de4-07deae4ba0f9.png)

and I am looking to remove all the borders except the outer one (the vertical-stack-in-card border).  I have now tried card_mod but nothing seems to work.  Card_mod does remove the outer border though, but that's the only one I want to keep.
