### ISSUE TITLE
Feature: Editor

### ISSUE THREAD

**Issue by acesyde** [ofekashery/vertical-stack-in-card#123]
Hi,

Could you add editor support in addition to YAML mode ?

**Comment by gilliginsisland** [comment]
providing gui editor support can be done by adding these lines to custom js 
```javascript
window.customElements.get('vertical-stack-in-card').getConfigElement = function() {
    return document.createElement('hui-stack-card-editor');
 }
```
It basically adds the required `getConfigElement` and then piggybacks on homeassistants built in editor for the horizontal and vertical stack cards.

**Comment by ofekashery** [comment]
Added in [v0.4.4](https://github.com/ofekashery/vertical-stack-in-card/releases/tag/v0.4.4).
