### ISSUE TITLE
Install instructions needs update

### ISSUE THREAD

**Issue by knwpsk** [ofekashery/vertical-stack-in-card#127]
(I'm new here)
Instructions for this mod say to edit UI.yaml and link it as a resource. 
HA prompts saying "Resources should be added in UI config instead" (paraphrased).

When I edit my dashboard, I see there's a menu item called "Resources" and it has a list of URLs. I assume we should add the URL for the .js file in this  mod, right?

I added it, copying the entire url (https://...card.js) but the card isn't available.  (Sidebar: the Resources page doesn't give me any indication whether the URL is valid; and the Developer Tools doesn't give me a way to test if the Resources list is valid, the way it does for Templates, etc. Would be nice to have that tool!)

Restarted HA to pick up the change, still not available. HA says "Custom element doesn't exist: vertical-stack-in-card."

**Comment by knwpsk** [comment]
apparently my issue isn't the first?
https://community.home-assistant.io/t/custom-element-doesnt-exist-vertical-stack-in-card/309707/6

**Comment by LucasHokerberg** [comment]
Download the JS file and put it in the /config/www folder of your HA installation.
Then, add the resource using the GUI as you where on to, but enter **/vertical-stack-in-card.js?v=0.4.1** as path (and select JavaScript Module).

That's it! :)

**Comment by knwpsk** [comment]
Yep that did it. Thanks Lucas.

**Comment by LucasHokerberg** [comment]
Please note my edit - you have to enter **/local/vertical-stack-in-card.js?v=0.4.1**, and not just **/vertical-stack-in-card.js?v=0.4.1**. For me, the later works fine using my desktop browser, but not in the Android app for some reason. Including **/local**, and it works in the Andoird app too. :)

**Comment by ofekashery** [comment]
Updated in #131.
