### ISSUE TITLE
[Issue] When using RBG with Alpha (transparency) channel get added, appearing darker

### ISSUE THREAD

**Issue by Maxi531** [ofekashery/vertical-stack-in-card#129]
![Screenshot 2022-07-18 000138](https://user-images.githubusercontent.com/82330572/179426399-f8fe58ed-9bed-4ce3-8f67-73d32a0cb502.png)

As you can see here, when using an alpha channel in background colors they get added together, making the whole card way darker, than it is supposed to be. 

Color it is supposed to be: rgba(10, 10, 10, 0.4)
I suspect the color now is (10, 10, 10, 0.8), but I'm not certain
Interestingly, the header gets treated differently, and is therefore not impacted

**Comment by Maxi531** [comment]
[FIX]
Use Card Mod to make the background of all cards clear, only leaving the title as is. 
Do this by adding 
`        card_mod:
          style: |
            ha-card { 
            background: rgba(10, 10, 10, 0);
            }`

**Comment by ofekashery** [comment]
Please use the [`styles` option](https://github.com/ofekashery/vertical-stack-in-card#options) as mentioned above.
