### ISSUE TITLE
v0.4.4: Cannot read properties of undefined (reading 'bind')

### ISSUE THREAD

**Issue by danielbrunt57** [ofekashery/vertical-stack-in-card#134]
Since v0.4.4 I cannot edit existing or add a new card...

![image](https://user-images.githubusercontent.com/49846893/198852875-50c7b5b4-c1c3-4cd1-a87d-c2bcff2d796d.png)

**Comment by pcprinz** [comment]
I had the same issue, but I resolved it by clearing the cache of my browser and reloading the page

**Comment by danielbrunt57** [comment]
I already tried that.  And just now I launched Chrome which I have never used for Home Assistant and have the same error message.

**Comment by eggman0131** [comment]
same issue here, clearing cache etc. doesn't help

**Comment by goyourfly** [comment]
same issue here, clearing cache etc. doesn't help

**Comment by danielbrunt57** [comment]
I no longer have that issue and I did nothing to resolve it, other than staying up to date with all updates in HA.  I don't know when the issue fixed itself...

**Comment by BBESINET** [comment]
I go around this by doing the following sequence:
- close the stackin-card I try to edit
- create a new card
- choose native grid or vertical  or horizontal card => the graphic interfaces pop up
- close this card (no need to save)
- open again my initial stack-in card "et voilà..."
