### ISSUE TITLE
Upgrade to 0.4.4, seems not to be loaded

### ISSUE THREAD

**Issue by kalhimeo** [ofekashery/vertical-stack-in-card#137]
Dear developer,

First thanks for your great card, I am using it everywhere in my HA installation :-D

I upgraded HA to 2022.11.0 today and read a few days ago in your changelog that version 0.4.4 should fix the new border problem. As it was not fixed for me after updating HA, I investigated and found that the visual card editor, which was also introduced in the last version of your repository, is not working either (HA load the manual edit window with the visual option grey out).

My initial thoughts were a cache problem, so I erased Edge's cache, but no luck. Then I uninstalled your addon via HACS, re-installed it, still no luck. To be really sure that the problem didn't come from by cache, I used my mobile phone to visit the HA url (I never browsed HA from there before, always used the Android app), and the problem was still there as well.

I also checked the version installed by directly opening the "\community\vertical-stack-in-card\vertical-stack-in-card.js" file and it says 0.4.4 in the top line.

Please let me know if you need more information for debugging.

PS: I have no error in HA logs either.

Best regards,
Laurent

**Comment by jmoery** [comment]
I seem to be having the same issue.  I can't get it to load in any version of HA past 2022.11.0

**Comment by muddro1** [comment]
Same problem. What I found was a temporary fix that doesn't stick:

1. Open the  Edit Dashboard
2. Edit the card (opens up to the code editor because visual editor does not work.)
3. Change card type to normal vertical-stack card
4. Change it back to 'custom:vertical-stack-in-card'

Now the Visual Editor should be accessible. But upon refresh it will switch back to greyed out.

**Comment by kalhimeo** [comment]
After reading #138 , I figured out that the problem is whenever the stack in card is nested inside any type of card as SinisterMedusa reported. His fix also works using card_mod :

```
card_mod:
  style: |
    ha-card {
      border: none;
    }
```
