### ISSUE TITLE
Card "Not loaded in lovelace" but works anyways ? 

### ISSUE THREAD

**Issue by Tontze** [ofekashery/vertical-stack-in-card#142]
HACS says that this card is not loaded in lovelace, and has red borders in it, it shows error, but it seems to be working anyways  ?

Fresh HA supervisor install, fresh HACS card install.

![image](https://user-images.githubusercontent.com/28216916/211209667-d9d041ce-8be2-49ba-9def-39a4484306d0.png)
![image](https://user-images.githubusercontent.com/28216916/211209681-5d498843-83a4-427f-a6b4-174c5eef84df.png)
![image](https://user-images.githubusercontent.com/28216916/211209705-b7f30614-85fb-4d45-b47a-fac3055d079c.png)

**Comment by Ali229** [comment]
+1 getting this same error, everything works fine, but annoying not loaded error

**Comment by ofekashery** [comment]
Duplicated of #146.
