### ISSUE TITLE
e is undefined

### ISSUE THREAD

**Issue by muddro1** [ofekashery/vertical-stack-in-card#145]
Frequently come up with this issue when trying to edit the card in the visual editor:

![image](https://user-images.githubusercontent.com/15880479/213750802-0962d09c-1f22-4cb5-907b-dd53be8e3639.png)

Doesn't allow me to edit visually but have to do it in yaml.

**Comment by muddro1** [comment]
Any potential on to fix this?

**Comment by ofekashery** [comment]
Duplicated of #146.
