### ISSUE TITLE
Errors while using the visual card editor

### ISSUE THREAD

**Issue by sbdobrescu** [ofekashery/vertical-stack-in-card#146]
Not sure if this is new or not... 

![stack](https://user-images.githubusercontent.com/14243948/217616259-c299838c-eb82-498b-9fca-4bc5202cbd39.png)

**Comment by sdrapha** [comment]
That is related to the pigbacking solution to have a UI editor for the card. 
The workaround solution is to EDIT another card, a regular vertical-stack. then come back to this card. once you load the native editor into cache. it's gonna keep working.

**Comment by MrChuckDanger** [comment]
> That is related to the pigbacking solution to have a UI editor for the card.
> The workaround solution is to EDIT another card, a regular vertical-stack. then come back to this card. once you load the native editor into cache. it's gonna keep working.

I can confirm this workaround works for me.
