### ISSUE TITLE
Card sometimes gets visually messed up 

### ISSUE THREAD

**Issue by backslashV** [ofekashery/vertical-stack-in-card#147]
If I refresh the page, it's fine again, but that's not the right solution. ![Screenshot_20230210-100556.png](https://user-images.githubusercontent.com/8752221/218164859-af2266bc-4063-4e90-a42e-425e9ea900d6.png)

![Screenshot_20230210-100900.png](https://user-images.githubusercontent.com/8752221/218164982-f424b0c5-2b14-4c04-93b7-487e7adcf8db.png)

**Comment by Ali229** [comment]
Can confirm this is happening to me as well, refreshing page fixes it, but annoying that it keeps happening

**Comment by StefaanT** [comment]
Have the same thing. Additionally, when using a dark theme, white areas become visible during refresh Hopefully it can be fixed.

Thanx in advance!

**Comment by ofekashery** [comment]
Duplicated of #150.
