### ISSUE TITLE
Custom element doesn't exist: vertical-stack-in-card.

### ISSUE THREAD

**Issue by HolgerBri** [ofekashery/vertical-stack-in-card#151]
Even with saving the .js in raw mode and empty browser cache I cannot use the card. Seems to be a common problem?
https://community.home-assistant.io/t/custom-element-doesnt-exist-vertical-stack-in-card/309707/8

**Comment by rursache** [comment]
it worked for me installing with HACS and reloading the browser tab when it asked me to. no other setup was required

**Comment by elylv** [comment]
Same issue here, installed via HACS but custom element not found.

**Comment by DarKOrange75** [comment]
Same here, it looks like the dev is no longer maintaining this card.

**Comment by soeffi** [comment]
You may want to look at https://github.com/custom-cards/stack-in-card as an alternative

**Comment by ofekashery** [comment]
Please make sure you follow the [installation instructions](https://github.com/ofekashery/vertical-stack-in-card#installation).
