### ISSUE TITLE
This._configElement.setConfig missing

### ISSUE THREAD

**Issue by erkr** [ofekashery/vertical-stack-in-card#152]
When I install this card in the most simple version. I see this error :

<img width="375" alt="image" src="https://github.com/ofekashery/vertical-stack-in-card/assets/4363599/95397e7a-f713-4665-a7da-e46271ef310d">

**Comment by lukyjay** [comment]
Save the card then go back into the editor

**Comment by erkr** [comment]
Close the issue as it doesn't reproduce anymore
