### ISSUE TITLE
Version mismatch - version 0.5.0 reports as 0.4.4

### ISSUE THREAD

**Issue by derMicro** [ofekashery/vertical-stack-in-card#163]
The version 0.5.0 reports in the browser console as 0.4.4, which could make it difficult to validate whether the correct version is installed and loaded.

Github
<img width="772" alt="image" src="https://github.com/user-attachments/assets/5de0377f-db9a-408b-88d5-6716f24ee622">

Browser
<img width="1387" alt="image" src="https://github.com/user-attachments/assets/2187a8bc-1ba2-4aaf-9597-bf91a11b2417">

**Comment by ofekashery** [comment]
Fixed.
