### ISSUE TITLE
[bug] no visual editor available

### ISSUE THREAD

**Issue by Silther** [ofekashery/vertical-stack-in-card#164]
![image](https://github.com/user-attachments/assets/71650d17-8317-4fa5-8929-597dad501b5a)

**Comment by ishbuggy** [comment]
I am getting the same error:
Configuration errors detected:

Cannot read properties of undefined (reading 'getConfigElement')

And so far the workaround to edit another working card then returning to this card does not work. I can set up the card once, and it continues to work, but the error prevents any further editing.

**Comment by pascalwinters** [comment]
Same here

**Comment by Oneshotblu** [comment]
Hi, similar isssue here, unable to save and apply the modifications due to " customElements.get(,,,) is undefined " error
![immagine](https://github.com/user-attachments/assets/c4d5ec58-82fb-44bc-97a7-32a2db7998b3)

**Comment by pctetra** [comment]
hello
i have the same problem randomly
to save, i temporarily replace
type: custom:vertical-stack-in-card
by
type: vertical-stack
and i put back
type: custom:vertical-stack-in-card

after this modification it disappears but it comes back after a while even by emptying the browser cache

vertical-stack-in-card version 0.5.0
home assistant Version core-2024.10.1

**Comment by BBE-FR** [comment]
Here, to get rid of this, i use the following workaround:

I face the same problem, from time to time, when opening or creating a vertical-stack-in-card. Ithose case I use the following sequence:
- Exit the card I try to modify.
- create a new card and select one of the core cards: "horizontal stack" or "vertical stack"
- the UI opens
- cancel the new card creation
- re-open the vertical-stack-in-card I wanted to create/modify => UI is back

**Comment by fabien4444** [comment]
Same bug here!

**Comment by dgongut** [comment]
Same bug here 🫡

**Comment by oleg-d** [comment]
following

**Comment by zain1144** [comment]
Same here.

I get this error
Configuration errors detected:
customElements.get(...) is undefined

I noticed when I click Add Card then cancel it the UI appears.

**Comment by samster395** [comment]
Also got the same issue but thankfully @zain1144's workaround sorts it out.

**Comment by xitters** [comment]
![image](https://github.com/user-attachments/assets/13c812b3-2c8d-43a7-a5c9-2ee55e17476e)
Same bug

**Comment by MPowerData** [comment]
Hi, any idea when this will be fixed? It is still occruring and makes editing the dashboard difficult.

**Comment by sharpsan** [comment]
Do we know what's causing this bug in the first place?

**Comment by kgraefe** [comment]
`hui-vertical-stack-card` is accessed before it is loaded

**Comment by ofekashery** [comment]
Fixed now, thanks :)

**Comment by xitters** [comment]
> Fixed now, thanks :)

Dont work for me with v 1.0.0

**Comment by xitters** [comment]
![image](https://github.com/user-attachments/assets/67902c40-13d7-4566-996c-503d437d7101)

![image](https://github.com/user-attachments/assets/07fd8236-2a0b-4e9c-9713-5f8c00e17f1a)

**Comment by kgraefe** [comment]
there's a follow-up issue for that: https://github.com/ofekashery/vertical-stack-in-card/issues/168
