### ISSUE TITLE
1.0.0 breaks editor (that's ironic) 

### ISSUE THREAD

**Issue by Salamandar** [ofekashery/vertical-stack-in-card#168]
`this.helpers is undefined` 

I suppose that comes from https://github.com/ofekashery/vertical-stack-in-card/pull/167/files#diff-ae21cda76b4d854107d86054a1d70451800fd9c0a3cd530a6c80d063141d191eR188

**Comment by kgraefe** [comment]
I was about to say the same thing. :-) specifically this commit breaks it since `helpers` is no longer lazy loaded: https://github.com/ofekashery/vertical-stack-in-card/pull/167/commits/db9307e77db5a8b878ed12e683f72380d200dc0c

**Comment by ofekashery** [comment]
Thanks for reporting, I've now released a fix for this issue!

**Comment by xitters** [comment]
> Thanks for reporting, I've now released a fix for this issue!

Excellent! works perfectly
