### ISSUE TITLE
`horizontal` line not persisting after opening card in editor

### ISSUE THREAD

**Issue by ScottG489** [ofekashery/vertical-stack-in-card#169]
I have a card with `horizontal: true,` but when I open it in the UI editor, that line seems to get removed.

This was also reported in a comment here: https://github.com/ofekashery/vertical-stack-in-card/issues/162#issuecomment-2542903204

I'm guessing this is a result of some recent changes. If you can't reproduce, let me know if there's more information I can provide!

**Comment by ofekashery** [comment]
Thanks for the report - I'm aware of this issue.

I'm working on a new solution which is introducing a new editor for the card. Hope to update soon!

**Comment by ofekashery** [comment]
Let's continue on issue #162.
