### ISSUE TITLE
Horizontal version

### ISSUE THREAD

**Issue by circa1665** [ofekashery/vertical-stack-in-card#39]
Could there be a horizontal version of this too?

**Comment by rgogada** [comment]
+1 for horizontal-stack-in-card

![image](https://user-images.githubusercontent.com/4284896/53136930-c5d43800-35d0-11e9-9819-8498a402bd89.png)

**Comment by rgogada** [comment]
here is the code

`card:
  cards:
    - cards:
        - card:
            artwork: full-cover
            background: /local/images/sonos_logo.png
            entity: media_player.frontroom_sonos
            hide_icon: true
            hide_media_info: true
            hide_mute: true
            hide_power: true
            name: Frontroom
            type: 'custom:mini-media-player'
          style:
            background-size: 100% 100%
            border-radius: 15px 0px 0px 0px
            overflow: hidden
          type: 'custom:card-modder'
        - card:
            artwork: full-cover
            background: /local/images/sonos_logo.png
            entity: media_player.kitchen_sonos
            hide_icon: true
            hide_media_info: true
            hide_mute: true
            hide_power: true
            name: Kitchen
            type: 'custom:mini-media-player'
          style:
            background-size: 100% 100%
            border-radius: 0px 0px 0px 0px
            overflow: hidden
          type: 'custom:card-modder'
        - card:
            artwork: full-cover
            background: /local/images/sonos_logo.png
            entity: media_player.lounge_sonos
            hide_icon: true
            hide_media_info: true
            hide_mute: true
            hide_power: true
            name: Lounge
            type: 'custom:mini-media-player'
          style:
            background-size: 100% 100%
            border-radius: 0px 15px 0px 0px
            overflow: hidden
          type: 'custom:card-modder'
      type: horizontal-stack
    - cards:
        - card:
            artwork: full-cover
            background: /local/images/sonos_logo.png
            entity: media_player.bedroom_sonos
            hide_icon: true
            hide_media_info: true
            hide_mute: true
            hide_power: true
            name: Bedroom
            type: 'custom:mini-media-player'
          style:
            background-size: 100% 100%
            border-radius: 0px 0px 0px 0px
            overflow: hidden
          type: 'custom:card-modder'
        - card:
            artwork: full-cover
            background: /local/images/sonos_logo.png
            entity: media_player.office_sonos
            hide_icon: true
            hide_media_info: true
            hide_mute: true
            hide_power: true
            name: Office
            type: 'custom:mini-media-player'
          style:
            background-size: 100% 100%
            border-radius: 0px 0px 0px 0px
            overflow: hidden
          type: 'custom:card-modder'
        - card:
            artwork: full-cover
            background: /local/images/sonos_logo.png
            entity: media_player.bathroom_sonos
            hide_icon: true
            hide_media_info: true
            hide_mute: true
            hide_power: true
            name: Bathroom
            type: 'custom:mini-media-player'
          style:
            background-size: 100% 100%
            border-radius: 0px 0px 0px 0px
            overflow: hidden
          type: 'custom:card-modder'
      type: horizontal-stack
    - cards:
        - card:
            artwork: full-cover
            background: /local/images/sonos_logo.png
            entity: media_player.rishiroom_sonos
            hide_icon: true
            hide_media_info: true
            hide_mute: true
            hide_power: true
            name: Rishiroom
            type: 'custom:mini-media-player'
          style:
            background-size: 100% 100%
            border-radius: 0px 0px 0px 15px
            overflow: hidden
          type: 'custom:card-modder'
        - card:
            artwork: full-cover
            background: /local/images/sonos_logo.png
            entity: media_player.office_amp
            hide_icon: true
            hide_media_info: true
            hide_mute: true
            hide_power: true
            name: Backyard
            type: 'custom:mini-media-player'
          style:
            background-size: 100% 100%
            border-radius: 0px 0px 0px 0px
            overflow: hidden
          type: 'custom:card-modder'
        - card:
            artwork: full-cover
            background: /local/images/sonos_logo.png
            entity: media_player.office_amp
            hide_icon: true
            hide_media_info: true
            hide_mute: true
            hide_power: true
            name: Guest
            type: 'custom:mini-media-player'
          style:
            background-size: 100% 100%
            border-radius: 0px 0px 15px 0px
            overflow: hidden
          type: 'custom:card-modder'
      type: horizontal-stack
  type: 'custom:vertical-stack-in-card'
id: Media
type: 'custom:card-modder'
`

**Comment by ofekashery** [comment]
Added in the [0.3.1](https://github.com/ofekashery/vertical-stack-in-card/releases/tag/v0.3.1) version  🎉
Just add ``horizontal: true`` to your card config.
