### ISSUE TITLE
Styling vertical-stack-in-card

### ISSUE THREAD

**Issue by jonostanck** [ofekashery/vertical-stack-in-card#50]
Would be great if there was `style: <list of styles>` to modify vertical-stack-in-card apperance. :)

**Comment by capstan1** [comment]
+1 from me. 
I'm using a theme with slight transparency. When using stack cards, every card has its own alpha (0.7), so it adds up to an alpha of 1. So what I get is this:
![image](https://user-images.githubusercontent.com/17147867/53697750-db1d4380-3dd4-11e9-9e32-781b7e67ff6f.png)

The header has the same transparency as the other cards. The cards itself have no transparency however.
I guess this should be avoided if there would be styling.

**Comment by capstan1** [comment]
Update: other styling attributes (like border radius) from the theme also aren't used for vertical-stack-card:
![image](https://user-images.githubusercontent.com/17147867/53969789-b0dfc480-40f9-11e9-8ce7-b6b58654fb04.png)

**Comment by tomlut** [comment]
I have the alpha issue but not the border radius issue.

**Comment by Spirituss** [comment]
I would also have such a feature. I use custom:button-card, grouped by vertical-stack-in-card. I didn't use any visible border for the buttons, but would like to have smoothed out borders of the stack.

**Comment by earion68** [comment]
> +1 from me.
> I'm using a theme with slight transparency. When using stack cards, every card has its own alpha (0.7), so it adds up to an alpha of 1. So what I get is this:
> ![image](https://user-images.githubusercontent.com/17147867/53697750-db1d4380-3dd4-11e9-9e32-781b7e67ff6f.png)
> 
> The header has the same transparency as the other cards. The cards itself have no transparency however.
> I guess this should be avoided if there would be styling.

I have the same issue I described [here](https://github.com/ofekashery/vertical-stack-in-card/issues/82)

**Comment by tomlut** [comment]
This can be solved with card-mod styling. 

https://github.com/thomasloven/lovelace-card-mod#mod-card

**Comment by logicup-dev** [comment]
tomlut:
> I have the alpha issue but not the border radius issue.
> 
> I think it is the cards we are putting in the stack that need to be set to 100% transparent background, not the stack-in-card background.

Thanks, solved this issue with a copy of the desired theme with a 100% transparent background. Apply this new theme to the cards inside the vertical-stack-in-card

**Comment by ofekashery** [comment]
Added in version [``4.0.1``](https://github.com/ofekashery/vertical-stack-in-card/releases/tag/v0.4.1) (see #110).
