### ISSUE TITLE
Support for Mobile apps

### ISSUE THREAD

**Issue by i00** [ofekashery/vertical-stack-in-card#65]
Would be greate if this supported mobile...
When viewed through the app, you get:
"custom:vertical-stack-in-card" card is not supported yet
The standard vertical stack supports this (just shows the individual components within it)

Thanks

**Comment by gitrummy** [comment]
Please provide a link to the mobile app you're using.

**Comment by gitrummy** [comment]
@i00 please provide a link to the mobile app you're using.
