### ISSUE TITLE
Error card not working

### ISSUE THREAD

**Issue by thomasloven** [ofekashery/vertical-stack-in-card#70]
Hi.
hui-error-card has become more picky about it's interface, so errors aren't displaying correctly...

The variable `config` needs to be renamed `origConfig` here:
https://github.com/custom-cards/vertical-stack-in-card/blob/master/vertical-stack-in-card.js#L35-L39

**Comment by MimbaMonkeyHouse** [comment]
Trying to use this card and struggling. Do you mean like this:
```
        const _createError = (error, config) => {
            return _createThing("hui-error-card", {
                type: "error",
                error,
                origConfig,
```

**Comment by thomasloven** [comment]
Both places
```javascript
        const _createError = (error, origConfig) => {
            return _createThing("hui-error-card", {
                type: "error",
                error,
                origConfig,
            });
        }
```
