### ISSUE TITLE
Custom element doesn't exist: hui-conditional-card.

### ISSUE THREAD

**Issue by veloc1ty** [ofekashery/vertical-stack-in-card#78]
Hi,

there seems to be a small problem with the vertical-stack-in-card after upgrading to 107.  The frontend throws an error "Custom element doesn't exist: hui-conditional-card. when using a "type: conditional" inside the custom:vertical-stack-in-card.

This does not happen when using the "normal" vertical-stack. The YAML for the section is fine, there is no hui-conditional-* referenced anywhere.

**Comment by Ernst79** [comment]
Had the same, but after a few refreshes and reloading the front panel it started to work again.

**Comment by fenik** [comment]
I've noticed the same behaviour with map cards.

Taking a wild guess, this might be the same issue as seen here: https://github.com/thomasloven/lovelace-fold-entity-row/issues/91

**Comment by wbilger** [comment]
I am experiencing the same problem, but I have noticed that the page will load correctly if I start at another page first, and then navigate to the problem page.
For me it seems to be when there is multiple picture-elements card inside a vertical-stack-in-card as I have 2 pages that act like that. I have one that does not, and it only has one picture-element card inside the vertical stack, this page works fine. Not sure if that is the issue or not, but seems to be for me. For now I will go back to 106.6 and keep an eye on this and test again later.

**Comment by SeLLeRoNe** [comment]
Same as this: https://github.com/ofekashery/vertical-stack-in-card/issues/75

Please also note, using the card-preloader (https://community.home-assistant.io/t/lovelace-card-preloader/176655) help you with the issue, of course it is not a fix but it's better than nothing for now :)

**Comment by RomRider** [comment]
@ofekashery, I can PR something to fix this issue but I had a more broad question: Are you still maintaining this card? Else I'd be happy to take over if we move it back to the `custom-cards` organisation.
Let me know what you think :)

**Comment by Poeschl** [comment]
More information about this bug from the HA repository: https://github.com/home-assistant/frontend/issues/4984

**Comment by aheath70** [comment]
I have the same issue here. I use the vertical stack in card quite a lot, and the it throws various errors for various cards nested with it. 
Custom element doesn't exist: hui-conditional-card.
Custom element doesn't exist: hui-pciture-entity-card.

etc.

**Comment by RomRider** [comment]
I've created a new card which is almost a drop-in replacement for vertical-stack-in-card and a bunch of other features:
https://community.home-assistant.io/t/stack-in-card-drop-in-replacement-for-vertical-stack-in-card/180072

**Comment by ofekashery** [comment]
@RomRider, I'm trying to still maintain it, mainly with PRs from the community, because I no longer use Home Assistant 😔.
The ``stack-in-card`` looks awesome, and I'd like to merge this card with your card.

**Comment by SeLLeRoNe** [comment]
Out of curiosity, what did you switch to? :)

**Comment by RomRider** [comment]
@ofekashery, stack-in-card is a complete rewrite in typescript. How do you see a merge?

**Comment by ofekashery** [comment]
@RomRider I mean, to release it as a new version of the card, and not as a separate card.

@SeLLeRoNe I built a whole system myself.

**Comment by RomRider** [comment]
In this case, you should move the repository to the custom-cards org, and give me rights on the repository. I'll rename it to stack in card and replace the code with the new one (and delete my repo)

**Comment by ofekashery** [comment]
Fixed in version [0.3.0](https://github.com/ofekashery/vertical-stack-in-card/releases/tag/v0.3.0), thanks!
