### ISSUE TITLE
Make card compatible with new vertical stack UI editor

### ISSUE THREAD

**Issue by SamPhoenix91** [ofekashery/vertical-stack-in-card#79]
The 107 updates meant the release of visual editors for vertical and horizontal stack cards. The editor should work perfectly and I have been told (on good authority) that custom cards are supported by the UI editor.

The stack UI should work perfectly with this.

**Comment by ikrowni** [comment]
I would like to see this feature added as well. The new editor is amazing.

**Comment by ttaidapos** [comment]
+1 This is huge.

**Comment by magenbrot** [comment]
Yes, that would be a big improvement. I'm using this card very much and this would help a lot :)

**Comment by flyingdutchman31** [comment]
+1 would be very usefull from a maintenance perspective

**Comment by JOHLC** [comment]
Visual editor would be excellent!

**Comment by ofekashery** [comment]
Added in [v0.4.4](https://github.com/ofekashery/vertical-stack-in-card/releases/tag/v0.4.4).
