### ISSUE TITLE
Issue with transparent backgrounds

### ISSUE THREAD

**Issue by earion68** [ofekashery/vertical-stack-in-card#82]
I have a transparent background set in my Home Assistant theme:

`ha-card-background: 'rgba(150, 150, 150, 0.2)'`

This is the behaviour of Vertical Stack In Cards:

![image](https://user-images.githubusercontent.com/54678154/77662253-ea40d780-6f7b-11ea-8cdf-8d93e727a03e.png)

**Comment by ofekashery** [comment]
See #110.
