### ISSUE TITLE
markdown card error

### ISSUE THREAD

**Issue by hcu00** [ofekashery/vertical-stack-in-card#83]
Hello,

Thank you for developping this nice card. :-)   I have a markdown card in my vertical-stack-in-card, but it gives an error "Custom element doesn't exist: hui-markdown-card.".

I have no markdown cards outside this v-s-i-c. If I place a markdown card at the top of the page, while outside v-s-i-c, it works perfectly without an error. However, as soon as a remove that 'outside' card, the error returns.

I am not sure were to post this error. I have the latest version of HASSIO etc.

Greetings,
Herco

**Comment by ofekashery** [comment]
@hcu00, Can you make sure you're using the [latest version](https://github.com/ofekashery/vertical-stack-in-card/releases/latest)?
Also, please add the new version number to the end of the cards reference url in your ``ui-lovelace.yaml``/``configuration.yaml`` like below:
```yaml
resources:
  - url: /local/vertical-stack-in-card.js?v=0.3.2
    type: js
```

**Comment by hcu00** [comment]
Thank you for the quick response. :-)   I did as you asked me to, and it works (v0.3.2). :-) Now, the markdown card is loaded and showed perfectly within v-s-i-c.

However, a new problem has arisen. I use the standard Lovelace horizontal stack cards within v-s-i-c. However, those cards have a border around them after the update.

**Comment by hcu00** [comment]
It seems to be shadow instead of a border. I can solve it by adding:
                style: |
                   ha-card {
                      box-shadow: none;
                    } 
to those card. I have the custom card-mod installed.

**Comment by hcu00** [comment]
But this behaviour regarding the shadow is new since the update, for me.

**Comment by ofekashery** [comment]
@hcu00, could you share your card config please?

**Comment by hcu00** [comment]
Hello, Sorry for the late response. It is still working fine. :-)  I have pasted a part of the lovelace file below. I am not a programmer, so if anybody has comments on my programming, please be kind... ;-)

--- --- ---
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:

          - title: 'Settings'
            type: custom:vertical-stack-in-card
            cards:
              - type: custom:vertical-stack-in-card
                style: |
                   ha-card {
                      box-shadow: none;
                    } 
                cards:
                  - type: markdown
                    content: 'Sensoren'
                    style: |
                      ha-card {
                        margin: 15px 0px -10px 0px;
                        font-size: 17px;
                      }
                  - type: horizontal-stack
                    cards:
                    - name: 'Douche Motion'
                      type: custom:button-card
                      entity: input_boolean.washokdouche_motion_sensor
                      icon: mdi:power-settings
                      size: 40px
                      show_label: false
                      show_state: true
                      layout: vertical
                      styles:
                        card:
                          - margin: 0px 10px 0px 0px
                          - padding: -20px 10px 0px 0px
                          - font-size: 14px
                          - font-weight: normal
                          - text-transform: none
                          - white-space: nowrap
                      state:
                        - value: 'on'
                          styles:
                            icon:
                              - color: rgb(45,114,178)
                        - value: 'off'
                          styles:
                            icon:
                              - color: rgb(128,0,0)
                      action: toggle
                    - name: 'Voordeur Thuiskomst'
                      type: custom:button-card
                      entity: input_boolean.voordeur_presence_sensor
                      icon: mdi:door-open
                      size: 40px
                      show_label: false
                      show_state: true
                      layout: vertical
                      styles:
                        card:
                          - margin: 0px 10px 0px 0px
                          - padding: -20px 10px 0px 0px
                          - font-size: 14px
                          - font-weight: normal
                          - text-transform: none
                          - white-space: nowrap
                      state:
                        - value: 'on'
                          styles:
                            icon:
                              - color: rgb(45,114,178)
                        - value: 'off'
                          styles:
                            icon:
                              - color: rgb(128,0,0)
                      action: toggle
                  - type: markdown
                    content: 'Lights'
                    style: |
                      ha-card {
                        margin: 15px 0px -10px 0px;
                        font-size: 17px;
                      }
                  - type: horizontal-stack
                    #title: 'Lights'
                    cards:
                    - label: 'Slaapkamer WakeUp Light'
                      type: custom:button-card
                      entity: input_boolean.slaapkamer_wake_up_light
                      icon: mdi:weather-sunset
                      size: 40px
                      show_label: false
                      show_state: true
                      layout: vertical
                      styles:
                        card:
                          - font-size: 14px
                          - font-weight: normal
                          - text-transform: none
                          - white-space: nowrap
                      state:
                        - value: 'on'
                          styles:
                            icon:
                              - color: rgb(45,114,178)
                        - value: 'off'
                          styles:
                            icon:
                              - color: rgb(128,0,0)
                      action: toggle
                    - name: 'Lang weg schedule'
                      type: custom:button-card
                      entity: input_boolean.lang_weg_sensor
                      icon: mdi:calendar-clock
                      size: 40px
                      show_label: false
                      show_state: true
                      layout: vertical
                      styles:
                        card:
                          - font-size: 14px
                          - font-weight: normal
                          - text-transform: none
                          - white-space: nowrap
                      state:
                        - value: 'on'
                          styles:
                            icon:
                              - color: rgb(45,114,178)
                        - value: 'off'
                          styles:
                            icon:
                              - color: rgb(128,0,0)
                      action: toggle
              - type: horizontal-stack
                cards:
                  - title: 'Dashboard Tablet'
                    type: glance
                    show_name: false
                    entities:
                      - entity: sensor.samsungtab4_battery_level
                        #icon: mdi:battery-50
                        tap_action: none
                      - entity: sensor.samsungtab4_charging
                        icon: mdi:battery-charging-100
                        tap_action: none
                      #- entity: input_select.samsungtab4_charge_mode
                      #  icon: mdi:power-settings
                      #  name: 'Charge mode'
                        #tap_action:
                        #  action: more_info
                    style: |
                      ha-card {
                        position: relative;
                        margin-right: -40px;
                        box-shadow: none;
                      }
                      .card-header {
                        font-size: 17px;
                      }
                  - name: 'Charge mode'
                    type: custom:button-card
                    entity: input_select.samsungtab4_charge_mode
                    icon: mdi:power-settings
                    size: 35px
                    show_name: true
                    show_label: false
                    show_state: true
                    layout: vertical
                    styles:
                      card:
                        - margin-top: 75px
                        - font-size: 14px
                    style: |
                       ha-card {
                          box-shadow: none;
                        }
                    state:
                      - value: 'Off'
                        icon: mdi:power-off 
                        color: rgb(128,0,0)
                      - value: 'Auto'
                        icon: mdi:power-cycle
                        color: rgb(45,114,178)
                      - value: 'On'
                        icon: mdi:power
                        color: rgb(0,99,0)
                    tap_action:
                      action: more-info
          - title: 'Overrule automations'
            type: custom:vertical-stack-in-card
            cards:
              - type: horizontal-stack
                cards:
                  - name: 'Aanwezig'
                    type: custom:button-card
                    entity: script.overrule_presence
                    icon: mdi:home-account
                    size: 40px
                    show_label: true
                    show_state: false
                    layout: vertical
                    styles:
                      card:
                        - font-size: 14px
                        - font-weight: normal
                        - text-transform: none
                        - white-space: nowrap
                    style: |
                       ha-card {
                          box-shadow: none;
                        }
                    state:
                      - value: 'on'
                        styles:
                          icon:
                            - color: rgb(140,140,140)
                      - value: 'off'
                        styles:
                          icon:
                            - color: rgb(140,140,140)
                    action: service
                    service:
                      domain: script
                      action: call-service
                      data:
                        entity_id: script.overrule_presence
                  - name: 'Washok-Douche Lichten'
                    type: custom:button-card
                    entity: input_boolean.washokdouche_overrule_lights
                    icon: mdi:lightbulb-on-outline
                    size: 40px
                    show_state: false
                    styles:
                      card:
                        - font-size: 14px
                        - font-weight: normal
                        - text-transform: none
                        - white-space: nowrap
                    style: |
                       ha-card {
                          box-shadow: none;
                        }
                    state:
                      - value: 'on'
                        styles:
                          icon:
                            - color: rgb(0,99,0)                          # voor blauw (45,114,178)
                      - value: 'off'
                        styles:
                          icon:
                            - color: rgb(140,140,140)
                    action: toggle

          - break

**Comment by ofekashery** [comment]
Please update to [the latest version](https://github.com/ofekashery/vertical-stack-in-card/releases/latest).
