### ISSUE TITLE
Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by gitrummy** [ofekashery/vertical-stack-in-card#90]
After updating to the latest HA Core 0.110.0 all cards using vertical stack in card show red with the error: maxium call stack size exceeded. Refreshing will momentarily 'fix' it, but the error comes back the next time you open the front end.
![Screenshot_20200521-181557](https://user-images.githubusercontent.com/11849147/82529682-ad661b00-9b8f-11ea-817e-06bc17a3e2af.jpg)

**Comment by papacrown** [comment]
I'm actually getting this as well, it usually disappears, and also getting the following in the browser console, it freezes up completely on Safari and Chrome takes a long time loading it. 
![Screen Shot 2020-05-21 at 12 46 34 PM](https://user-images.githubusercontent.com/22719066/82590000-95c46d80-9b62-11ea-89a4-f8ee99de3f73.png)

**Comment by zang74** [comment]
I just came to post about the same thing that papacrown just mentioned. HUI seems to just get caught in a loop of this error, and eats browser resources like mad. A browser cache clearing or straight up new login generally works fine, but after a page reload or two (cmd-R). This problem doesn't happen in Chrome, but Safari and the HomeAssistant iOS app (which I assume is also using Safari at its core).

**Comment by zang74** [comment]
I'd note that I'm also using a slightly older version of chrome (80.0.3987.122). Weirdly I do get a red card with "Maximum call stack size exceeded" when I reload a page (community, map, etc.), then move back to the overview.

**Comment by papacrown** [comment]
Good to know I'm not alone, should I create a new issue? I think it's related to @gitrummy 's issue since I am also getting that error. 

@zang74 I'm on Chrome 81.0.4044.138

**Comment by zang74** [comment]
So, I've managed to get a usable HASS again by switching all my vertical-stack-in-card to straight vertical-stack.

No problems after that. So it definitely is an issue with this plugin. I've got practically zero experience with Javascript, so I'm of little help in fixing this. Will revisit this plugin if the issue gets fixed.

**Comment by nenadmilano** [comment]
Same issue here, reloading lovelace takes ages and puts the following output in the browser console.
Happens in Chrome on macOS aswell as in the Home Assistant iOS App.

![image](https://user-images.githubusercontent.com/32328649/82750128-64d87880-9dae-11ea-850c-e174fa347f58.png)

![image](https://user-images.githubusercontent.com/32328649/82750113-54c09900-9dae-11ea-9115-07b852f0a724.png)

**Comment by ofekashery** [comment]
I'm running Home Assistant 0.110.3 and cannot reproduce, could anyone share his ``vertical-stack-in-card`` config please?

**Comment by nenadmilano** [comment]
It seems that i had an old version of vertical-stack-in-card installed because HACS did not recognise the install any more. Updated the plugin and now it works properly.

**Comment by ofekashery** [comment]
@gitrummy @papacrown Can you make sure you run the ``vertical-stack-in-card`` **0.3.3** please?
You should see this massage in the DevTools Console.
![image](https://user-images.githubusercontent.com/16443111/83107693-5e584280-a0c7-11ea-8a6d-52fa43725279.png)

**Comment by ofekashery** [comment]
As @nenadmilano said, please **make sure HACS is using the latest version** of ``vertical-stack-in-card``.
