### ISSUE TITLE
Since 0.166 stacked cards do not appear until dashboard is edited and the X clicked

### ISSUE THREAD

**Issue by grantalewis** [ofekashery/vertical-stack-in-card#96]
Config: Firefox 81.0.1 on Mac OS Catalina 10.15.7, HA frontend version: 20201001.2. Problem: Stacked entity cards do not show until I click the three vertical dots in the upper right and then click the X in the upper left.

**Comment by grantalewis** [comment]
I think this problem has resolved itself. Will reopen if I discover otherwise.

**Comment by grantalewis** [comment]
Still seeing this as an issue, running 0.116.4.

**Comment by vando** [comment]
Still happen in 0.117.

**Comment by kampf-schaf** [comment]
Have the same issue in Lovelace with iobroker. Sometimes it appears and often it disappears.

**Comment by ofekashery** [comment]
Fixed in [``v0.4.0``](https://github.com/ofekashery/vertical-stack-in-card/releases/tag/v0.4.0) 🎉
